#pragma once

#ifdef __cplusplus
extern "C" {
#endif

enum midpar_ExprType {
    // num literals
    MIDPAR_EXPRTYPE_NUMLIT_START,
    MIDPAR_EXPRTYPE_CHAR_LIT,
    MIDPAR_EXPRTYPE_WCHAR_LIT,
    MIDPAR_EXPRTYPE_CHAR16_LIT,
    MIDPAR_EXPRTYPE_CHAR32_LIT,
    MIDPAR_EXPRTYPE_STRING_LIT,
    MIDPAR_EXPRTYPE_WSTRING_LIT,
    MIDPAR_EXPRTYPE_STRING16_LIT,
    MIDPAR_EXPRTYPE_STRING32_LIT,
    MIDPAR_EXPRTYPE_INT_LIT,
    MIDPAR_EXPRTYPE_UINT_LIT,
    MIDPAR_EXPRTYPE_LONG_LIT,
    MIDPAR_EXPRTYPE_ULONG_LIT,
    MIDPAR_EXPRTYPE_LONGLONG_LIT,
    MIDPAR_EXPRTYPE_ULONGLONG_LIT,
    MIDPAR_EXPRTYPE_FLTLIT_START,
    MIDPAR_EXPRTYPE_FLOAT_LIT,
    MIDPAR_EXPRTYPE_DOUBLE_LIT,
    MIDPAR_EXPRTYPE_LONGDOUBLE_LIT,
    MIDPAR_EXPRTYPE_FLTLIT_END,
    MIDPAR_EXPRTYPE_BOOL_LIT, // true, false
    MIDPAR_EXPRTYPE_NULLPTR_LIT,
    MIDPAR_EXPRTYPE_NUMLIT_END,

    MIDPAR_EXPRTYPE_CONST_FOLD, // a constant folded expressio node

    MIDPAR_EXPRTYPE_IDENTIFIER,
    MIDPAR_EXPRTYPE_THIS,

    // ternary ops
    MIDPAR_EXPRTYPE_TERNARYOP_START,
    MIDPAR_EXPRTYPE_CONDITIONAL,
    MIDPAR_EXPRTYPE_TERNARYOP_END,

    // binary ops
    MIDPAR_EXPRTYPE_BINOP_START,
    MIDPAR_EXPRTYPE_BIN_SCOPE_RES, // example: A::X
    MIDPAR_EXPRTYPE_MEMB_SEL,
    MIDPAR_EXPRTYPE_PTR_MEMB_SEL,
    MIDPAR_EXPRTYPE_ARRAY_SUBSCR,
    MIDPAR_EXPRTYPE_NEW_ARR,
    MIDPAR_EXPRTYPE_DELETE_ARR,
    MIDPAR_EXPRTYPE_PTR_TO_MEMB_SEL,
    MIDPAR_EXPRTYPE_PTR_TO_PTR_MEMB_SEL,
    MIDPAR_EXPRTYPE_MUL,
    MIDPAR_EXPRTYPE_DIV,
    MIDPAR_EXPRTYPE_MOD,
    MIDPAR_EXPRTYPE_ADD,
    MIDPAR_EXPRTYPE_SUB,
    MIDPAR_EXPRTYPE_LEFT_SHIFT,
    MIDPAR_EXPRTYPE_RIGHT_SHIFT,
    MIDPAR_EXPRTYPE_LT,
    MIDPAR_EXPRTYPE_GT,
    MIDPAR_EXPRTYPE_LTEQ,
    MIDPAR_EXPRTYPE_GTEQ,
    MIDPAR_EXPRTYPE_EQ,
    MIDPAR_EXPRTYPE_NEQ,
    MIDPAR_EXPRTYPE_BITWISE_AND,
    MIDPAR_EXPRTYPE_BITWISE_XOR,
    MIDPAR_EXPRTYPE_BITWISE_OR,
    MIDPAR_EXPRTYPE_LOGICAL_AND,
    MIDPAR_EXPRTYPE_LOGICAL_OR,
    MIDPAR_EXPRTYPE_ASSIGN,
    MIDPAR_EXPRTYPE_MUL_ASSIGN,
    MIDPAR_EXPRTYPE_DIV_ASSIGN,
    MIDPAR_EXPRTYPE_MOD_ASSIGN,
    MIDPAR_EXPRTYPE_ADD_ASSIGN,
    MIDPAR_EXPRTYPE_SUB_ASSIGN,
    MIDPAR_EXPRTYPE_LEFT_SHIFT_ASSIGN,
    MIDPAR_EXPRTYPE_RIGHT_SHIFT_ASSIGN,
    MIDPAR_EXPRTYPE_AND_ASSIGN,
    MIDPAR_EXPRTYPE_OR_ASSIGN,
    MIDPAR_EXPRTYPE_XOR_ASSIGN,
    MIDPAR_EXPRTYPE_COMMA,
    MIDPAR_EXPRTYPE_BINOP_END,

    // unary ops
    MIDPAR_EXPRTYPE_UNARYOP_START,
    MIDPAR_EXPRTYPE_UNARY_SCOPE_RES, // example: ::X
    MIDPAR_EXPRTYPE_FUNC_CALL,       // not really a unary operator but close
                                     // enough
    MIDPAR_EXPRTYPE_POSTFIX_INC,
    MIDPAR_EXPRTYPE_POSTFIX_DEC,
    MIDPAR_EXPRTYPE_TYPEID,
    MIDPAR_EXPRTYPE_CONSTCAST,
    MIDPAR_EXPRTYPE_DYNAMICCAST,
    MIDPAR_EXPRTYPE_REINTERPRETCAST,
    MIDPAR_EXPRTYPE_STATICCAST,
    MIDPAR_EXPRTYPE_SIZEOF,
    MIDPAR_EXPRTYPE_PREFIX_INC,
    MIDPAR_EXPRTYPE_PREFIX_DEC,
    MIDPAR_EXPRTYPE_BITWISE_NOT,
    MIDPAR_EXPRTYPE_LOGICAL_NOT,
    MIDPAR_EXPRTYPE_UNARY_PLUS,
    MIDPAR_EXPRTYPE_UNARY_MINUS,
    MIDPAR_EXPRTYPE_DEREF,
    MIDPAR_EXPRTYPE_REF,
    MIDPAR_EXPRTYPE_NEW,
    MIDPAR_EXPRTYPE_DELETE,
    MIDPAR_EXPRTYPE_CAST,
    MIDPAR_EXPRTYPE_THROW,
    MIDPAR_EXPRTYPE_UNARYOP_END,
};

const char *midpar_exprtype_name(enum midpar_ExprType type);

#ifdef __cplusplus
}
#endif
