#pragma once

enum Lexer_TokenType {
    LEXER_TOKENTYPE_END,

    LEXER_TOKENTYPE_TERNARYOP_START,
    LEXER_TOKENTYPE_CONDITIONAL,
    LEXER_TOKENTYPE_TERNARYOP_END,

    LEXER_TOKENTYPE_BINOP_START,
    LEXER_TOKENTYPE_SCOPE_RES,
    LEXER_TOKENTYPE_MEMB_SEL,            // a.b
    LEXER_TOKENTYPE_PTR_MEMB_SEL,        // a->b
    LEXER_TOKENTYPE_PTR_TO_MEMB_SEL,     // a.*b
    LEXER_TOKENTYPE_PTR_TO_PTR_MEMB_SEL, // a->*b
    LEXER_TOKENTYPE_MUL,                 // can also be unary dereference
    LEXER_TOKENTYPE_DIV,
    LEXER_TOKENTYPE_MOD,
    LEXER_TOKENTYPE_ADD, // can also be unary
    LEXER_TOKENTYPE_SUB, // can also be unary
    LEXER_TOKENTYPE_LEFT_SHIFT,
    LEXER_TOKENTYPE_RIGHT_SHIFT,
    LEXER_TOKENTYPE_LT,          // <
    LEXER_TOKENTYPE_GT,          // >
    LEXER_TOKENTYPE_LTEQ,        // <=
    LEXER_TOKENTYPE_GTEQ,        // >=
    LEXER_TOKENTYPE_EQ,          // ==
    LEXER_TOKENTYPE_NEQ,         // !=
    LEXER_TOKENTYPE_BITWISE_AND, // can also be unary reference
    LEXER_TOKENTYPE_BITWISE_XOR,
    LEXER_TOKENTYPE_BITWISE_OR,
    LEXER_TOKENTYPE_LOGICAL_AND,
    LEXER_TOKENTYPE_LOGICAL_OR,
    LEXER_TOKENTYPE_ASSIGN,
    LEXER_TOKENTYPE_MUL_ASSIGN,
    LEXER_TOKENTYPE_DIV_ASSIGN,
    LEXER_TOKENTYPE_MOD_ASSIGN,
    LEXER_TOKENTYPE_ADD_ASSIGN,
    LEXER_TOKENTYPE_SUB_ASSIGN,
    LEXER_TOKENTYPE_LEFT_SHIFT_ASSIGN,
    LEXER_TOKENTYPE_RIGHT_SHIFT_ASSIGN,
    LEXER_TOKENTYPE_AND_ASSIGN,
    LEXER_TOKENTYPE_XOR_ASSIGN,
    LEXER_TOKENTYPE_OR_ASSIGN,
    LEXER_TOKENTYPE_COMMA,
    LEXER_TOKENTYPE_BINOP_END,

    LEXER_TOKENTYPE_UNARYOP_START,
    LEXER_TOKENTYPE_INC,
    LEXER_TOKENTYPE_DEC,
    LEXER_TOKENTYPE_TYPEID,
    LEXER_TOKENTYPE_CONSTCAST,
    LEXER_TOKENTYPE_DYNAMICCAST,
    LEXER_TOKENTYPE_REINTERPRETCAST,
    LEXER_TOKENTYPE_STATICCAST,
    LEXER_TOKENTYPE_SIZEOF,
    LEXER_TOKENTYPE_BITWISE_NOT,
    LEXER_TOKENTYPE_LOGICAL_NOT,
    LEXER_TOKENTYPE_NEW,
    LEXER_TOKENTYPE_DELETE,
    LEXER_TOKENTYPE_THROW,
    LEXER_TOKENTYPE_UNARYOP_END,

    LEXER_TOKENTYPE_NUMLIT_START,
    LEXER_TOKENTYPE_CHAR_LIT,
    LEXER_TOKENTYPE_WCHAR_LIT,
    LEXER_TOKENTYPE_CHAR16_LIT,
    LEXER_TOKENTYPE_CHAR32_LIT,
    LEXER_TOKENTYPE_INT_LIT,
    LEXER_TOKENTYPE_UINT_LIT,
    LEXER_TOKENTYPE_LONG_LIT,
    LEXER_TOKENTYPE_ULONG_LIT,
    LEXER_TOKENTYPE_LONGLONG_LIT,
    LEXER_TOKENTYPE_ULONGLONG_LIT,
    LEXER_TOKENTYPE_FLOAT_LIT,
    LEXER_TOKENTYPE_DOUBLE_LIT,
    LEXER_TOKENTYPE_LONGDOUBLE_LIT,
    LEXER_TOKENTYPE_BOOL_LIT, // true, false
    LEXER_TOKENTYPE_NULLPTR_LIT,
    LEXER_TOKENTYPE_NUMLIT_END,

    LEXER_TOKENTYPE_STRLIT_START,
    LEXER_TOKENTYPE_STRING_LIT,
    LEXER_TOKENTYPE_WSTRING_LIT,
    LEXER_TOKENTYPE_STRING16_LIT,
    LEXER_TOKENTYPE_STRING32_LIT,
    LEXER_TOKENTYPE_STRLIT_END,

    LEXER_TOKENTYPE_L_PAREN,
    LEXER_TOKENTYPE_R_PAREN,
    LEXER_TOKENTYPE_L_SQBRACKET,
    LEXER_TOKENTYPE_R_SQBRACKET,
    LEXER_TOKENTYPE_L_CURLY,
    LEXER_TOKENTYPE_R_CURLY,

    LEXER_TOKENTYPE_COLON,
    LEXER_TOKENTYPE_SEMICOLON,
    LEXER_TOKENTYPE_ELLIPSIS,

    LEXER_TOKENTYPE_IDENTIFIER,

    LEXER_TOKENTYPE_THIS,

    LEXER_TOKENTYPE_NAMESPACE,

    LEXER_TOKENTYPE_RETURN,

    LEXER_TOKENTYPE_TYPESPEC_START,
    LEXER_TOKENTYPE_VOID,
    LEXER_TOKENTYPE_CHAR,
    LEXER_TOKENTYPE_WCHAR,
    LEXER_TOKENTYPE_CHAR16,
    LEXER_TOKENTYPE_CHAR32,
    LEXER_TOKENTYPE_BOOL,
    LEXER_TOKENTYPE_INT,
    LEXER_TOKENTYPE_FLOAT,
    LEXER_TOKENTYPE_DOUBLE,
    LEXER_TOKENTYPE_STRUCT,
    LEXER_TOKENTYPE_CLASS,
    LEXER_TOKENTYPE_UNION,
    LEXER_TOKENTYPE_ENUM,
    LEXER_TOKENTYPE_AUTO,
    LEXER_TOKENTYPE_TYPESPEC_END,

    LEXER_TOKENTYPE_TYPEMOD_START,
    LEXER_TOKENTYPE_SHORT,
    LEXER_TOKENTYPE_LONG,
    LEXER_TOKENTYPE_SIGNED,
    LEXER_TOKENTYPE_UNSIGNED,
    LEXER_TOKENTYPE_TYPEMOD_END,

    // type storage qualifiers
    LEXER_TOKENTYPE_TYPESTORQUAL_START,
    LEXER_TOKENTYPE_STATIC,
    LEXER_TOKENTYPE_CONSTEXPR,
    LEXER_TOKENTYPE_TYPEDEF, // believe it or not
    LEXER_TOKENTYPE_TYPESTORQUAL_END,

    LEXER_TOKENTYPE_TYPEDATAQUAL_START,
    LEXER_TOKENTYPE_CONST,
    LEXER_TOKENTYPE_VOLATILE,
    LEXER_TOKENTYPE_TYPEDATAQUAL_END,

    LEXER_TOKENTYPE_NOEXCEPT,
    LEXER_TOKENTYPE_FINAL,
    LEXER_TOKENTYPE_OVERRIDE,

    LEXER_TOKENTYPE_DEFAULT,

    LEXER_TOKENTYPE_ACCESSSPEC_START,
    LEXER_TOKENTYPE_PUBLIC,
    LEXER_TOKENTYPE_PRIVATE,
    LEXER_TOKENTYPE_PROTECTED,
    LEXER_TOKENTYPE_ACCESSSPEC_END,
};
