#pragma once

#include "generics/dynarray.h"
#include "literal.h"
#include "position.h"

enum Lexer_TokenType {
    LEXER_TOKENTYPE_END,

    LEXER_TOKENTYPE_TERNARYOP_START,
    LEXER_TOKENTYPE_CONDITIONAL,
    LEXER_TOKENTYPE_TERNARYOP_END,

    LEXER_TOKENTYPE_BINOP_START,
    LEXER_TOKENTYPE_SCOPE_RES,
    LEXER_TOKENTYPE_MEMB_SEL,            // a.b
    LEXER_TOKENTYPE_PTR_MEMB_SEL,        // a->b
    LEXER_TOKENTYPE_PTR_TO_MEMB_SEL,     // a.*b
    LEXER_TOKENTYPE_PTR_TO_PTR_MEMB_SEL, // a->*b
    LEXER_TOKENTYPE_MUL,                 // can also be unary dereference
    LEXER_TOKENTYPE_DIV,
    LEXER_TOKENTYPE_MOD,
    LEXER_TOKENTYPE_ADD, // can also be unary
    LEXER_TOKENTYPE_SUB, // can also be unary
    LEXER_TOKENTYPE_LEFT_SHIFT,
    LEXER_TOKENTYPE_RIGHT_SHIFT,
    LEXER_TOKENTYPE_LT,          // <
    LEXER_TOKENTYPE_GT,          // >
    LEXER_TOKENTYPE_LTEQ,        // <=
    LEXER_TOKENTYPE_GTEQ,        // >=
    LEXER_TOKENTYPE_EQ,          // ==
    LEXER_TOKENTYPE_NEQ,         // !=
    LEXER_TOKENTYPE_BITWISE_AND, // can also be unary reference
    LEXER_TOKENTYPE_BITWISE_XOR,
    LEXER_TOKENTYPE_BITWISE_OR,
    LEXER_TOKENTYPE_LOGICAL_AND,
    LEXER_TOKENTYPE_LOGICAL_OR,
    LEXER_TOKENTYPE_ASSIGN,
    LEXER_TOKENTYPE_MUL_ASSIGN,
    LEXER_TOKENTYPE_DIV_ASSIGN,
    LEXER_TOKENTYPE_MOD_ASSIGN,
    LEXER_TOKENTYPE_ADD_ASSIGN,
    LEXER_TOKENTYPE_SUB_ASSIGN,
    LEXER_TOKENTYPE_LEFT_SHIFT_ASSIGN,
    LEXER_TOKENTYPE_RIGHT_SHIFT_ASSIGN,
    LEXER_TOKENTYPE_AND_ASSIGN,
    LEXER_TOKENTYPE_XOR_ASSIGN,
    LEXER_TOKENTYPE_OR_ASSIGN,
    LEXER_TOKENTYPE_COMMA,
    LEXER_TOKENTYPE_BINOP_END,

    LEXER_TOKENTYPE_UNARYOP_START,
    LEXER_TOKENTYPE_INC,
    LEXER_TOKENTYPE_DEC,
    LEXER_TOKENTYPE_TYPEID,
    LEXER_TOKENTYPE_CONSTCAST,
    LEXER_TOKENTYPE_DYNAMICCAST,
    LEXER_TOKENTYPE_REINTERPRETCAST,
    LEXER_TOKENTYPE_STATICCAST,
    LEXER_TOKENTYPE_SIZEOF,
    LEXER_TOKENTYPE_BITWISE_NOT,
    LEXER_TOKENTYPE_LOGICAL_NOT,
    LEXER_TOKENTYPE_NEW,
    LEXER_TOKENTYPE_DELETE,
    LEXER_TOKENTYPE_THROW,
    LEXER_TOKENTYPE_UNARYOP_END,

    LEXER_TOKENTYPE_NUMLIT_START,
    LEXER_TOKENTYPE_INT_LIT,
    LEXER_TOKENTYPE_UINT_LIT,
    LEXER_TOKENTYPE_LONG_LIT,
    LEXER_TOKENTYPE_ULONG_LIT,
    LEXER_TOKENTYPE_LONGLONG_LIT,
    LEXER_TOKENTYPE_ULONGLONG_LIT,
    LEXER_TOKENTYPE_FLOAT_LIT,
    LEXER_TOKENTYPE_DOUBLE_LIT,
    LEXER_TOKENTYPE_LONGDOUBLE_LIT,
    LEXER_TOKENTYPE_BOOL_LIT, // true, false
    LEXER_TOKENTYPE_PTR_LIT,  // nullptr
    LEXER_TOKENTYPE_NUMLIT_END,

    LEXER_TOKENTYPE_L_PAREN,
    LEXER_TOKENTYPE_R_PAREN,
    LEXER_TOKENTYPE_L_SQBRACKET,
    LEXER_TOKENTYPE_R_SQBRACKET,
    LEXER_TOKENTYPE_L_CURLY,
    LEXER_TOKENTYPE_R_CURLY,

    LEXER_TOKENTYPE_COLON,
    LEXER_TOKENTYPE_SEMICOLON,

    LEXER_TOKENTYPE_IDENTIFIER,

    LEXER_TOKENTYPE_TYPESPEC_START,
    LEXER_TOKENTYPE_CHAR,
    LEXER_TOKENTYPE_WCHAR,
    LEXER_TOKENTYPE_CHAR16,
    LEXER_TOKENTYPE_CHAR32,
    LEXER_TOKENTYPE_BOOL,
    LEXER_TOKENTYPE_INT,
    LEXER_TOKENTYPE_FLOAT,
    LEXER_TOKENTYPE_DOUBLE,
    LEXER_TOKENTYPE_STRUCT,
    LEXER_TOKENTYPE_CLASS,
    LEXER_TOKENTYPE_UNION,
    LEXER_TOKENTYPE_ENUM,
    LEXER_TOKENTYPE_TYPESPEC_END,

    LEXER_TOKENTYPE_TYPEMOD_START,
    LEXER_TOKENTYPE_SHORT,
    LEXER_TOKENTYPE_LONG,
    LEXER_TOKENTYPE_SIGNED,
    LEXER_TOKENTYPE_UNSIGNED,
    LEXER_TOKENTYPE_TYPEMOD_END,

    // type storage qualifiers
    LEXER_TOKENTYPE_TYPESTORQUAL_START,
    LEXER_TOKENTYPE_STATIC,
    LEXER_TOKENTYPE_CONSTEXPR,
    LEXER_TOKENTYPE_TYPEDEF, // believe it or not
    LEXER_TOKENTYPE_TYPESTORQUAL_END,

    LEXER_TOKENTYPE_TYPEDATAQUAL_START,
    LEXER_TOKENTYPE_CONST,
    LEXER_TOKENTYPE_TYPEDATAQUAL_END,
};

bool Lexer_is_numlit(enum Lexer_TokenType type);
bool Lexer_is_lit(enum Lexer_TokenType type);
bool Lexer_is_ternaryop(enum Lexer_TokenType type);
bool Lexer_is_binop(enum Lexer_TokenType type);
bool Lexer_is_unaryop(enum Lexer_TokenType type);
// operators that can be unary (eg. LEXER_TOKENTYPE_SUB can be in a - b and -b)
bool Lexer_can_be_unary(enum Lexer_TokenType type);
bool Lexer_is_op(enum Lexer_TokenType type);
bool Lexer_is_typespec(enum Lexer_TokenType type);
// class, struct, union and enum
bool Lexer_is_named_typespec(enum Lexer_TokenType type);
bool Lexer_is_typestorqual(enum Lexer_TokenType type);
bool Lexer_is_typedataqual(enum Lexer_TokenType type);
bool Lexer_is_typequal(enum Lexer_TokenType type);
// signed, unsigned, short and long
bool Lexer_is_typemod(enum Lexer_TokenType type);

struct Lexer_Token {
    union {
        union Literal_Value val;
        const char *ident;
    };
    struct Position pos;
    const char *line;
    enum Lexer_TokenType type;
};
gen_dynarray_struct_named(Lexer_TokenVec, struct Lexer_Token);
