#pragma once

enum MidLexer_TokenType {
    MIDLEXER_TOKENTYPE_END,

    MIDLEXER_TOKENTYPE_TERNARYOP_START,
    MIDLEXER_TOKENTYPE_CONDITIONAL,
    MIDLEXER_TOKENTYPE_TERNARYOP_END,

    MIDLEXER_TOKENTYPE_BINOP_START,
    MIDLEXER_TOKENTYPE_SCOPE_RES,
    MIDLEXER_TOKENTYPE_MEMB_SEL,            // a.b
    MIDLEXER_TOKENTYPE_PTR_MEMB_SEL,        // a->b
    MIDLEXER_TOKENTYPE_PTR_TO_MEMB_SEL,     // a.*b
    MIDLEXER_TOKENTYPE_PTR_TO_PTR_MEMB_SEL, // a->*b
    MIDLEXER_TOKENTYPE_MUL,                 // can also be unary dereference
    MIDLEXER_TOKENTYPE_DIV,
    MIDLEXER_TOKENTYPE_MOD,
    MIDLEXER_TOKENTYPE_ADD, // can also be unary
    MIDLEXER_TOKENTYPE_SUB, // can also be unary
    MIDLEXER_TOKENTYPE_LEFT_SHIFT,
    MIDLEXER_TOKENTYPE_RIGHT_SHIFT,
    MIDLEXER_TOKENTYPE_LT,          // <
    MIDLEXER_TOKENTYPE_GT,          // >
    MIDLEXER_TOKENTYPE_LTEQ,        // <=
    MIDLEXER_TOKENTYPE_GTEQ,        // >=
    MIDLEXER_TOKENTYPE_EQ,          // ==
    MIDLEXER_TOKENTYPE_NEQ,         // !=
    MIDLEXER_TOKENTYPE_BITWISE_AND, // can also be unary reference
    MIDLEXER_TOKENTYPE_BITWISE_XOR,
    MIDLEXER_TOKENTYPE_BITWISE_OR,
    MIDLEXER_TOKENTYPE_LOGICAL_AND,
    MIDLEXER_TOKENTYPE_LOGICAL_OR,
    MIDLEXER_TOKENTYPE_ASSIGN,
    MIDLEXER_TOKENTYPE_MUL_ASSIGN,
    MIDLEXER_TOKENTYPE_DIV_ASSIGN,
    MIDLEXER_TOKENTYPE_MOD_ASSIGN,
    MIDLEXER_TOKENTYPE_ADD_ASSIGN,
    MIDLEXER_TOKENTYPE_SUB_ASSIGN,
    MIDLEXER_TOKENTYPE_LEFT_SHIFT_ASSIGN,
    MIDLEXER_TOKENTYPE_RIGHT_SHIFT_ASSIGN,
    MIDLEXER_TOKENTYPE_AND_ASSIGN,
    MIDLEXER_TOKENTYPE_XOR_ASSIGN,
    MIDLEXER_TOKENTYPE_OR_ASSIGN,
    MIDLEXER_TOKENTYPE_COMMA,
    MIDLEXER_TOKENTYPE_BINOP_END,

    MIDLEXER_TOKENTYPE_UNARYOP_START,
    MIDLEXER_TOKENTYPE_INC,
    MIDLEXER_TOKENTYPE_DEC,
    MIDLEXER_TOKENTYPE_TYPEID,
    MIDLEXER_TOKENTYPE_CONSTCAST,
    MIDLEXER_TOKENTYPE_DYNAMICCAST,
    MIDLEXER_TOKENTYPE_REINTERPRETCAST,
    MIDLEXER_TOKENTYPE_STATICCAST,
    MIDLEXER_TOKENTYPE_SIZEOF,
    MIDLEXER_TOKENTYPE_BITWISE_NOT,
    MIDLEXER_TOKENTYPE_LOGICAL_NOT,
    MIDLEXER_TOKENTYPE_NEW,
    MIDLEXER_TOKENTYPE_DELETE,
    MIDLEXER_TOKENTYPE_THROW,
    MIDLEXER_TOKENTYPE_UNARYOP_END,

    MIDLEXER_TOKENTYPE_NUMMIDLIT_START,
    MIDLEXER_TOKENTYPE_CHAR_LIT,
    MIDLEXER_TOKENTYPE_WCHAR_LIT,
    MIDLEXER_TOKENTYPE_CHAR16_LIT,
    MIDLEXER_TOKENTYPE_CHAR32_LIT,
    MIDLEXER_TOKENTYPE_INT_LIT,
    MIDLEXER_TOKENTYPE_UINT_LIT,
    MIDLEXER_TOKENTYPE_LONG_LIT,
    MIDLEXER_TOKENTYPE_ULONG_LIT,
    MIDLEXER_TOKENTYPE_LONGLONG_LIT,
    MIDLEXER_TOKENTYPE_ULONGLONG_LIT,
    MIDLEXER_TOKENTYPE_FLOAT_LIT,
    MIDLEXER_TOKENTYPE_DOUBLE_LIT,
    MIDLEXER_TOKENTYPE_LONGDOUBLE_LIT,
    MIDLEXER_TOKENTYPE_BOOL_LIT, // true, false
    MIDLEXER_TOKENTYPE_NULLPTR_LIT,
    MIDLEXER_TOKENTYPE_NUMMIDLIT_END,

    MIDLEXER_TOKENTYPE_STRMIDLIT_START,
    MIDLEXER_TOKENTYPE_STRING_LIT,
    MIDLEXER_TOKENTYPE_WSTRING_LIT,
    MIDLEXER_TOKENTYPE_STRING16_LIT,
    MIDLEXER_TOKENTYPE_STRING32_LIT,
    MIDLEXER_TOKENTYPE_STRMIDLIT_END,

    MIDLEXER_TOKENTYPE_L_PAREN,
    MIDLEXER_TOKENTYPE_R_PAREN,
    MIDLEXER_TOKENTYPE_L_SQBRACKET,
    MIDLEXER_TOKENTYPE_R_SQBRACKET,
    MIDLEXER_TOKENTYPE_L_CURLY,
    MIDLEXER_TOKENTYPE_R_CURLY,

    MIDLEXER_TOKENTYPE_COLON,
    MIDLEXER_TOKENTYPE_SEMICOLON,
    MIDLEXER_TOKENTYPE_ELLIPSIS,

    MIDLEXER_TOKENTYPE_IDENTIFIER,

    MIDLEXER_TOKENTYPE_THIS,

    MIDLEXER_TOKENTYPE_NAMESPACE,

    MIDLEXER_TOKENTYPE_RETURN,

    MIDLEXER_TOKENTYPE_TYPESPEC_START,
    MIDLEXER_TOKENTYPE_VOID,
    MIDLEXER_TOKENTYPE_CHAR,
    MIDLEXER_TOKENTYPE_WCHAR,
    MIDLEXER_TOKENTYPE_CHAR16,
    MIDLEXER_TOKENTYPE_CHAR32,
    MIDLEXER_TOKENTYPE_BOOL,
    MIDLEXER_TOKENTYPE_INT,
    MIDLEXER_TOKENTYPE_FLOAT,
    MIDLEXER_TOKENTYPE_DOUBLE,
    MIDLEXER_TOKENTYPE_STRUCT,
    MIDLEXER_TOKENTYPE_CLASS,
    MIDLEXER_TOKENTYPE_UNION,
    MIDLEXER_TOKENTYPE_ENUM,
    MIDLEXER_TOKENTYPE_AUTO,
    MIDLEXER_TOKENTYPE_TYPESPEC_END,

    MIDLEXER_TOKENTYPE_TYPEMOD_START,
    MIDLEXER_TOKENTYPE_SHORT,
    MIDLEXER_TOKENTYPE_LONG,
    MIDLEXER_TOKENTYPE_SIGNED,
    MIDLEXER_TOKENTYPE_UNSIGNED,
    MIDLEXER_TOKENTYPE_TYPEMOD_END,

    // type storage qualifiers
    MIDLEXER_TOKENTYPE_TYPESTORQUAL_START,
    MIDLEXER_TOKENTYPE_STATIC,
    MIDLEXER_TOKENTYPE_CONSTEXPR,
    MIDLEXER_TOKENTYPE_TYPEDEF, // believe it or not
    MIDLEXER_TOKENTYPE_TYPESTORQUAL_END,

    MIDLEXER_TOKENTYPE_TYPEDATAQUAL_START,
    MIDLEXER_TOKENTYPE_CONST,
    MIDLEXER_TOKENTYPE_VOLATILE,
    MIDLEXER_TOKENTYPE_TYPEDATAQUAL_END,

    MIDLEXER_TOKENTYPE_NOEXCEPT,
    MIDLEXER_TOKENTYPE_FINAL,
    MIDLEXER_TOKENTYPE_OVERRIDE,

    MIDLEXER_TOKENTYPE_TEMPLATE,
    MIDLEXER_TOKENTYPE_TYPENAME,

    MIDLEXER_TOKENTYPE_DEFAULT,

    MIDLEXER_TOKENTYPE_ACCESSSPEC_START,
    MIDLEXER_TOKENTYPE_PUBLIC,
    MIDLEXER_TOKENTYPE_PRIVATE,
    MIDLEXER_TOKENTYPE_PROTECTED,
    MIDLEXER_TOKENTYPE_ACCESSSPEC_END,
};

#define MIDLEXER_TTALIAS_L_ANGLE MIDLEXER_TOKENTYPE_LT
#define MIDLEXER_TTALIAS_R_ANGLE MIDLEXER_TOKENTYPE_GT
