#pragma once

#include "generics/dynarray.h"
#include "position.h"

enum ErrorType {
    ERRORTYPE_UNKNOWN_SYMBOL,
    ERRORTYPE_MISSING_PAREN,
    ERRORTYPE_MISSING_SQBRACKET,
    ERRORTYPE_MISSING_CURLY,
    ERRORTYPE_INSUFFICIENT_OPERANDS,
    ERRORTYPE_MISSING_TYPESPEC,
    ERRORTYPE_TYPE_UNSIGNABLE,
    ERRORTYPE_MISSING_IDENTIFIER,
    ERRORTYPE_PTR_TO_REF,
    ERRORTYPE_MISPLACED_QUALIFIER,
    ERRORTYPE_TYPE_ALREADY_REF,
    ERRORTYPE_UNEXPECTED_TOKEN,
    ERRORTYPE_MISSING_TOKEN,
    ERRORTYPE_TYPEDEF_MISSING_NAME,
    ERRORTYPE_MISSING_SEMICOLON,
    ERRORTYPE_UNDECLARED_IDENTIFIER,
    ERRORTYPE_BAD_IDENTIFIER,
    ERRORTYPE_BAD_ARRAY_SUBSCRIPT,
    ERRORTYPE_BAD_ASSIGNMENT,
    ERRORTYPE_BAD_DEREF,
    ERRORTYPE_BAD_REF,
    ERRORTYPE_BAD_CONDITIONAL,
    ERRORTYPE_BAD_ARITHMETIC_OP,
    ERRORTYPE_BAD_LOGICAL_OP,
    ERRORTYPE_BAD_COMPARISON_OP,
    ERRORTYPE_BAD_OP_OVERLOAD,
    ERRORTYPE_BAD_SUPERCLASS,
    ERRORTYPE_BAD_VAR_DECLARATION,
};

enum WarnType {
    WARNTYPE_UNNECESSARY_QUALIFIER,
};

struct Diag {
    struct Position pos;
    const char *line; // terminated by '\n'
    char *msg;
    union {
        enum ErrorType err;
        enum WarnType warn;
    };
    bool is_err;
};
gen_dynarray_struct_named(DiagVec, struct Diag);

void Diag_deinit(struct Diag *self);
void Diag_print(const struct Diag *diag);
