#pragma once

enum midlex_TokenType {
    MIDLEX_TOKENTYPE_END,

    MIDLEX_TOKENTYPE_TERNARYOP_START,
    MIDLEX_TOKENTYPE_CONDITIONAL,
    MIDLEX_TOKENTYPE_TERNARYOP_END,

    MIDLEX_TOKENTYPE_BINOP_START,
    MIDLEX_TOKENTYPE_SCOPE_RES,
    MIDLEX_TOKENTYPE_MEMB_SEL,            // a.b
    MIDLEX_TOKENTYPE_PTR_MEMB_SEL,        // a->b
    MIDLEX_TOKENTYPE_PTR_TO_MEMB_SEL,     // a.*b
    MIDLEX_TOKENTYPE_PTR_TO_PTR_MEMB_SEL, // a->*b
    MIDLEX_TOKENTYPE_MUL,                 // can also be unary dereference
    MIDLEX_TOKENTYPE_DIV,
    MIDLEX_TOKENTYPE_MOD,
    MIDLEX_TOKENTYPE_ADD, // can also be unary
    MIDLEX_TOKENTYPE_SUB, // can also be unary
    MIDLEX_TOKENTYPE_LEFT_SHIFT,
    MIDLEX_TOKENTYPE_RIGHT_SHIFT,
    MIDLEX_TOKENTYPE_LT,          // <
    MIDLEX_TOKENTYPE_GT,          // >
    MIDLEX_TOKENTYPE_LTEQ,        // <=
    MIDLEX_TOKENTYPE_GTEQ,        // >=
    MIDLEX_TOKENTYPE_EQ,          // ==
    MIDLEX_TOKENTYPE_NEQ,         // !=
    MIDLEX_TOKENTYPE_BITWISE_AND, // can also be unary reference
    MIDLEX_TOKENTYPE_BITWISE_XOR,
    MIDLEX_TOKENTYPE_BITWISE_OR,
    MIDLEX_TOKENTYPE_LOGICAL_AND,
    MIDLEX_TOKENTYPE_LOGICAL_OR,
    MIDLEX_TOKENTYPE_ASSIGN,
    MIDLEX_TOKENTYPE_MUL_ASSIGN,
    MIDLEX_TOKENTYPE_DIV_ASSIGN,
    MIDLEX_TOKENTYPE_MOD_ASSIGN,
    MIDLEX_TOKENTYPE_ADD_ASSIGN,
    MIDLEX_TOKENTYPE_SUB_ASSIGN,
    MIDLEX_TOKENTYPE_LEFT_SHIFT_ASSIGN,
    MIDLEX_TOKENTYPE_RIGHT_SHIFT_ASSIGN,
    MIDLEX_TOKENTYPE_AND_ASSIGN,
    MIDLEX_TOKENTYPE_XOR_ASSIGN,
    MIDLEX_TOKENTYPE_OR_ASSIGN,
    MIDLEX_TOKENTYPE_COMMA,
    MIDLEX_TOKENTYPE_BINOP_END,

    MIDLEX_TOKENTYPE_UNARYOP_START,
    MIDLEX_TOKENTYPE_INC,
    MIDLEX_TOKENTYPE_DEC,
    MIDLEX_TOKENTYPE_TYPEID,
    MIDLEX_TOKENTYPE_CONSTCAST,
    MIDLEX_TOKENTYPE_DYNAMICCAST,
    MIDLEX_TOKENTYPE_REINTERPRETCAST,
    MIDLEX_TOKENTYPE_STATICCAST,
    MIDLEX_TOKENTYPE_SIZEOF,
    MIDLEX_TOKENTYPE_BITWISE_NOT,
    MIDLEX_TOKENTYPE_LOGICAL_NOT,
    MIDLEX_TOKENTYPE_NEW,
    MIDLEX_TOKENTYPE_DELETE,
    MIDLEX_TOKENTYPE_THROW,
    MIDLEX_TOKENTYPE_UNARYOP_END,

    MIDLEX_TOKENTYPE_NUMMIDLIT_START,
    MIDLEX_TOKENTYPE_CHAR_LIT,
    MIDLEX_TOKENTYPE_WCHAR_LIT,
    MIDLEX_TOKENTYPE_CHAR16_LIT,
    MIDLEX_TOKENTYPE_CHAR32_LIT,
    MIDLEX_TOKENTYPE_INT_LIT,
    MIDLEX_TOKENTYPE_UINT_LIT,
    MIDLEX_TOKENTYPE_LONG_LIT,
    MIDLEX_TOKENTYPE_ULONG_LIT,
    MIDLEX_TOKENTYPE_LONGLONG_LIT,
    MIDLEX_TOKENTYPE_ULONGLONG_LIT,
    MIDLEX_TOKENTYPE_FLOAT_LIT,
    MIDLEX_TOKENTYPE_DOUBLE_LIT,
    MIDLEX_TOKENTYPE_LONGDOUBLE_LIT,
    MIDLEX_TOKENTYPE_BOOL_LIT, // true, false
    MIDLEX_TOKENTYPE_NULLPTR_LIT,
    MIDLEX_TOKENTYPE_NUMMIDLIT_END,

    MIDLEX_TOKENTYPE_STRMIDLIT_START,
    MIDLEX_TOKENTYPE_STRING_LIT,
    MIDLEX_TOKENTYPE_WSTRING_LIT,
    MIDLEX_TOKENTYPE_STRING16_LIT,
    MIDLEX_TOKENTYPE_STRING32_LIT,
    MIDLEX_TOKENTYPE_STRMIDLIT_END,

    MIDLEX_TOKENTYPE_L_PAREN,
    MIDLEX_TOKENTYPE_R_PAREN,
    MIDLEX_TOKENTYPE_L_SQBRACKET,
    MIDLEX_TOKENTYPE_R_SQBRACKET,
    MIDLEX_TOKENTYPE_L_CURLY,
    MIDLEX_TOKENTYPE_R_CURLY,

    MIDLEX_TOKENTYPE_COLON,
    MIDLEX_TOKENTYPE_SEMICOLON,
    MIDLEX_TOKENTYPE_ELLIPSIS,

    MIDLEX_TOKENTYPE_IDENTIFIER,

    MIDLEX_TOKENTYPE_THIS,

    MIDLEX_TOKENTYPE_NAMESPACE,

    MIDLEX_TOKENTYPE_RETURN,

    MIDLEX_TOKENTYPE_TYPESPEC_START,
    MIDLEX_TOKENTYPE_VOID,
    MIDLEX_TOKENTYPE_CHAR,
    MIDLEX_TOKENTYPE_WCHAR,
    MIDLEX_TOKENTYPE_CHAR16,
    MIDLEX_TOKENTYPE_CHAR32,
    MIDLEX_TOKENTYPE_BOOL,
    MIDLEX_TOKENTYPE_INT,
    MIDLEX_TOKENTYPE_FLOAT,
    MIDLEX_TOKENTYPE_DOUBLE,
    MIDLEX_TOKENTYPE_STRUCT,
    MIDLEX_TOKENTYPE_CLASS,
    MIDLEX_TOKENTYPE_UNION,
    MIDLEX_TOKENTYPE_ENUM,
    MIDLEX_TOKENTYPE_AUTO,
    MIDLEX_TOKENTYPE_TYPESPEC_END,

    MIDLEX_TOKENTYPE_TYPEMOD_START,
    MIDLEX_TOKENTYPE_SHORT,
    MIDLEX_TOKENTYPE_LONG,
    MIDLEX_TOKENTYPE_SIGNED,
    MIDLEX_TOKENTYPE_UNSIGNED,
    MIDLEX_TOKENTYPE_TYPEMOD_END,

    // type storage qualifiers
    MIDLEX_TOKENTYPE_TYPESTORQUAL_START,
    MIDLEX_TOKENTYPE_STATIC,
    MIDLEX_TOKENTYPE_CONSTEXPR,
    MIDLEX_TOKENTYPE_TYPEDEF, // believe it or not
    MIDLEX_TOKENTYPE_TYPESTORQUAL_END,

    MIDLEX_TOKENTYPE_TYPEDATAQUAL_START,
    MIDLEX_TOKENTYPE_CONST,
    MIDLEX_TOKENTYPE_VOLATILE,
    MIDLEX_TOKENTYPE_TYPEDATAQUAL_END,

    MIDLEX_TOKENTYPE_NOEXCEPT,
    MIDLEX_TOKENTYPE_FINAL,
    MIDLEX_TOKENTYPE_OVERRIDE,

    MIDLEX_TOKENTYPE_TEMPLATE,
    MIDLEX_TOKENTYPE_TYPENAME,

    MIDLEX_TOKENTYPE_DEFAULT,

    MIDLEX_TOKENTYPE_ACCESSSPEC_START,
    MIDLEX_TOKENTYPE_PUBLIC,
    MIDLEX_TOKENTYPE_PRIVATE,
    MIDLEX_TOKENTYPE_PROTECTED,
    MIDLEX_TOKENTYPE_ACCESSSPEC_END,
};

#define MIDLEX_TTALIAS_L_ANGLE MIDLEX_TOKENTYPE_LT
#define MIDLEX_TTALIAS_R_ANGLE MIDLEX_TOKENTYPE_GT
